name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run ./cypress/e2e/App.cy.js
        uses: cypress-io/github-action@v4
        with:
          working-directory: ./frontend
          install: npm ci
          start: npm start
